name: .NET Build

on:
  push:
    branches:
      - main  # ou outro branch que deseja monitorar
  schedule:
    - cron: '0 * * * *'  # A cada hora (em UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # substitua pela versão desejada

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar
        run: dotnet build --configuration Release

      - name: Rodar testes
        run: dotnet test --no-build --verbosity normal    

